name: SonarCloud analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust the Node.js version as needed

      - name: Install Dependencies and Angular CLI
        run: |
          npm install -force
          npm install -g @angular/cli

      - name: Build Angular app
        run: ng build --configuration=production

      - name: Analyze with SonarCloud
        if: ${{ github.event_name != 'pull_request' }}
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN1 }}
        with:
          args:
            -Dsonar.projectKey=manushacampus_final_year_project_web
            -Dsonar.organization=manushacampus
            -Dsonar.sources=src

      - name: Run Snyk for Dependency Scanning
        uses: snyk/actions/node@v1
        with:
          command: test

      - name: Upload Snyk Results
        uses: actions/upload-artifact@v2
        with:
          name: snyk-results
          path: .snyk
